DATASET:
  root_dataset: "./data/"
  list_train: "./data/training.odgt"
  list_val: "./data/validation.odgt"
  num_class: 150
  imgSizes: (512, )
  imgMaxSize: 1000
  padding_constant: 2
  segm_downsampling_rate: 2
  random_flip: True

MODEL:
  arch_encoder: "resnet50dilated16"
  arch_decoder: "acnet"
  fc_dim: 2048

TRAIN:
  batch_size_per_gpu: 5
  num_epoch: 25
  start_epoch: 0
  epoch_iters: 5000
  optim: "SGD"
  lr_encoder: 0.02
  lr_decoder: 0.02
  lr_pow: 0.9
  beta1: 0.9
  weight_decay: 1e-4
  deep_sup_scale: 0.4
  fix_bn: False
  workers: 16
  disp_iter: 20
  seed: 304

VAL:
  visualize: False
  checkpoint: "epoch_25.pth"

TEST:
  checkpoint: "epoch_25.pth"
  result: "./"

DIR: "ckpt/ade20k-acnet50"
