DATASET:
  root_dataset: "./data/"
  list_train: "./data/training.odgt"
  list_val: "./data/validation.odgt"
  num_class: 150
  imgSizes: (512, )
  imgMaxSize: 1000
  padding_constant: 32
  segm_downsampling_rate: 4
  random_flip: True

MODEL:
  arch_encoder: "resnet101"
  arch_decoder: "upernet"
  fc_dim: 2048
  weights_encoder: "ckpt/ade20k-resnet101-upernet/encoder_epoch_50.pth"
  weights_decoder: "ckpt/ade20k-resnet101-upernet/decoder_epoch_50.pth"

TRAIN:
  batch_size_per_gpu: 2
  num_epoch: 5
  start_epoch: 0
  epoch_iters: 10000
  optim: "Adam"
  lr_encoder: 1e-6
  lr_decoder: 1e-6
  lr_pow: 0.9
  beta1: 0.9
  weight_decay: 1e-4
  deep_sup_scale: 0.4
  fix_bn: True
  workers: 16
  disp_iter: 20
  step_iter: 1
  seed: 304

VAL:
  visualize: False
  checkpoint: "epoch_5.pth"

TEST:
  checkpoint: "epoch_5.pth"
  result: "./"

DIR: "ckpt/finetune-ade20k-resnet101-upernet"
